import requests
from bs4 import BeautifulSoup
import csv

links = [
  "https://climateinitiativesplatform.org/index.php/100_Resilient_Cities",
  "https://climateinitiativesplatform.org/index.php/2050_Pathways_Platform",
  "https://climateinitiativesplatform.org/index.php/21st_Century_Truck_Partnership",
  "https://climateinitiativesplatform.org/index.php/4_:_1000_-_Soils_for_Food_Security_and_Climate",
  "https://climateinitiativesplatform.org/index.php/ACT_Assessing_Low-Carbon_Transition",
  "https://climateinitiativesplatform.org/index.php/Action_towards_Climate_Friendly_Transport",
  "https://climateinitiativesplatform.org/index.php/Adaptation_for_Smallholder_Agriculture_Programme",
  "https://climateinitiativesplatform.org/index.php/Adaptation_of_West_African_Coastal_Areas",
  "https://climateinitiativesplatform.org/index.php/Africa_Renewable_Energy_Initiative",
  "https://climateinitiativesplatform.org/index.php/African_Adaptation_Initiative_(AAI)",
  "https://climateinitiativesplatform.org/index.php/African_Forest_landscape_Restoration_(AFR100)",
  "https://climateinitiativesplatform.org/index.php/AgSTAR",
  "https://climateinitiativesplatform.org/index.php/Airport_Carbon_Accreditation_(ACI)",
  "https://climateinitiativesplatform.org/index.php/Alliance_for_an_Energy_Efficient_Economy_(AEEE)",
  "https://climateinitiativesplatform.org/index.php/Alliance_for_Climate_Action",
  "https://climateinitiativesplatform.org/index.php/Alliance_for_Global_Water_Adaptation_(AGWA)",
  "https://climateinitiativesplatform.org/index.php/Alliance_for_Responsible_Atmospheric_Policy",
  "https://climateinitiativesplatform.org/index.php/America%E2%80%99s_Pledge",
  "https://climateinitiativesplatform.org/index.php/Association_for_Supporting_the_SDGs_for_the_UN_(ASD)",
  "https://climateinitiativesplatform.org/index.php/B_Corp_Climate_Collective",
  "https://climateinitiativesplatform.org/index.php/Banking_Environment_Initiative_(BEI)",
  "https://climateinitiativesplatform.org/index.php/Below50",
  "https://climateinitiativesplatform.org/index.php/BioCarbon_Fund_Initiative_for_Sustainable_Forest_Landscapes_(ISFL)",
  "https://climateinitiativesplatform.org/index.php/Blue_Growth_Initiative",
  "https://climateinitiativesplatform.org/index.php/Bonn_Challenge_-_Landscape_Restoration",
  "https://climateinitiativesplatform.org/index.php/Breakthrough_Energy_Coalition",
  "https://climateinitiativesplatform.org/index.php/Business_Alliance_for_Water_and_Climate",
  "https://climateinitiativesplatform.org/index.php/Business_Environmental_Leadership_Council_(BELC)",
  "https://climateinitiativesplatform.org/index.php/Business_Leadership_Criteria_on_Carbon_Pricing",
  "https://climateinitiativesplatform.org/index.php/C40_Cities_Climate_Leadership_Group_(C40)",
  "https://climateinitiativesplatform.org/index.php/C40_Clean_Bus_Declaration",
  "https://climateinitiativesplatform.org/index.php/C40_Zero_Waste_Declaration",
  "https://climateinitiativesplatform.org/index.php/Carbon_Neutral_Cities_Alliance",
  "https://climateinitiativesplatform.org/index.php/Carbon_Neutrality_Coalition",
  "https://climateinitiativesplatform.org/index.php/Carbon_Pricing_Leadership_Coalition",
  "https://climateinitiativesplatform.org/index.php/Carbon_Sequestration_Leadership_Forum_(CSLF)",
  "https://climateinitiativesplatform.org/index.php/Carbon_War_Room_Shipping_Initiative",
  "https://climateinitiativesplatform.org/index.php/Carbonn_Cities_Climate_Registry_(cCCR)",
  "https://climateinitiativesplatform.org/index.php/Caring_for_Climate",
  "https://climateinitiativesplatform.org/index.php/CCAC:_Agriculture_Initiative",
  "https://climateinitiativesplatform.org/index.php/CCAC:_Bricks_Initiative",
  "https://climateinitiativesplatform.org/index.php/CCAC:_Climate_and_Clean_Air_Coalition_(Main)",
  "https://climateinitiativesplatform.org/index.php/CCAC:_Global_Green_Freight_Action_Plan",
  "https://climateinitiativesplatform.org/index.php/CCAC:_Oil_%26_Gas_Methane_Partnership",
  "https://climateinitiativesplatform.org/index.php/CCAC:_Phasing_Down_Climate_Potent_HFCs_/_HFCs_Initiative",
  "https://climateinitiativesplatform.org/index.php/CCAC:_Waste,_Mitigating_SLCPs_from_the_Municipal_Solid_Waste_Sector",
  "https://climateinitiativesplatform.org/index.php/CEM:_Clean_Energy_Ministerial",
  "https://climateinitiativesplatform.org/index.php/CEM:_Global_Lighting_Challenge",
  "https://climateinitiativesplatform.org/index.php/Central_African_Forest_Initiative_(CAFI)",
  "https://climateinitiativesplatform.org/index.php/Central_American_Integration_System_Initiative_(SICA)",
  "https://climateinitiativesplatform.org/index.php/CGIAR_Research_Program_on_Climate_Change,_Agriculture_and_Food_Security_(CCAFS)",
  "https://climateinitiativesplatform.org/index.php/Cities_and_regions_5-year_vision",
  "https://climateinitiativesplatform.org/index.php/Cities_Climate_Finance_Leadership_Alliance_(the_Alliance)",
  "https://climateinitiativesplatform.org/index.php/Clean_Air_Asia",
  "https://climateinitiativesplatform.org/index.php/Clean_Air_Fund",
  "https://climateinitiativesplatform.org/index.php/Clean_Air_Initiative",
  "https://climateinitiativesplatform.org/index.php/Clean_by_Design",
  "https://climateinitiativesplatform.org/index.php/Clean_Energy_Buyers_Association_-_CEBA",
  "https://climateinitiativesplatform.org/index.php/Clean_Energy_Corridors_in_Africa",
  "https://climateinitiativesplatform.org/index.php/CLG_Europe",
  "https://climateinitiativesplatform.org/index.php/Climate_Action_100%2B",
  "https://climateinitiativesplatform.org/index.php/Climate_Action_for_Jobs_Initiative",
  "https://climateinitiativesplatform.org/index.php/Climate_Action_in_Financial_Institutions",
  "https://climateinitiativesplatform.org/index.php/Climate_Alliance",
  "https://climateinitiativesplatform.org/index.php/Climate_Ambition_Alliance:_Net_Zero_2050",
  "https://climateinitiativesplatform.org/index.php/Climate_Ambition_Alliance:_Race_to_Zero",
  "https://climateinitiativesplatform.org/index.php/Climate_and_Development_Knowledge_Network_(CDKN)",
  "https://climateinitiativesplatform.org/index.php/Climate_and_Land_Use_Alliance_(CLUA)",
  "https://climateinitiativesplatform.org/index.php/Climate_Change_Impacts_on_Cultural_and_Natural_Heritage_(CCICH)",
  "https://climateinitiativesplatform.org/index.php/Climate_Investment_Platform",
  "https://climateinitiativesplatform.org/index.php/Climate_Land_Ambition_and_Rights_Alliance_(CLARA)",
  "https://climateinitiativesplatform.org/index.php/Climate_Neutral_Now",
  "https://climateinitiativesplatform.org/index.php/Climate_Risk_and_Early_Warning_Systems_Initiative",
  "https://climateinitiativesplatform.org/index.php/Climate_Smart_Agriculture_Booster_(CSA_Booster)",
  "https://climateinitiativesplatform.org/index.php/Climate,_Community_and_Biodiversity_Alliance_(CCBA)",
  "https://climateinitiativesplatform.org/index.php/Climate-KIC",
  "https://climateinitiativesplatform.org/index.php/ClimateWise",
  "https://climateinitiativesplatform.org/index.php/Clinton_Climate_Initiative",
  "https://climateinitiativesplatform.org/index.php/Coalition_for_Climate_resilient_Investment_(CCRI)",
  "https://climateinitiativesplatform.org/index.php/Coalition_for_Sustainable_Energy_Access_(CSEA)",
  "https://climateinitiativesplatform.org/index.php/Collaborative_Climate_Action_Across_the_Air_Transport_World",
  "https://climateinitiativesplatform.org/index.php/Collaborative_Partnership_on_Forests_(CPF)",
  "https://climateinitiativesplatform.org/index.php/Community-Based_Adaptation_Network_(CBA_Network)",
  "https://climateinitiativesplatform.org/index.php/Compact_of_Mayors",
  "https://climateinitiativesplatform.org/index.php/Conference_of_Peripheral_Maritime_Regions",
  "https://climateinitiativesplatform.org/index.php/Cool_Coalition",
  "https://climateinitiativesplatform.org/index.php/Covenant_of_Mayors_for_Climate_%26_Energy",
  "https://climateinitiativesplatform.org/index.php/Cycling_Delivers_on_the_Global_Goals",
  "https://climateinitiativesplatform.org/index.php/Decarbonizing_Shipping:_Getting_to_Zero_Coalition",
  "https://climateinitiativesplatform.org/index.php/Divest-Invest_Global_Movement",
  "https://climateinitiativesplatform.org/index.php/EcoMobility_Alliance",
  "https://climateinitiativesplatform.org/index.php/EcoPartnerships",
  "https://climateinitiativesplatform.org/index.php/En.lighten_Initiative",
  "https://climateinitiativesplatform.org/index.php/Energy_Cities",
  "https://climateinitiativesplatform.org/index.php/EP100",
  "https://climateinitiativesplatform.org/index.php/EuroACE",
  "https://climateinitiativesplatform.org/index.php/EUROCITIES",
  "https://climateinitiativesplatform.org/index.php/European_Alliance_to_Save_Energy_(EU-ASE)",
  "https://climateinitiativesplatform.org/index.php/European_Cyclists%27_Federation_advocacy_efforts",
  "https://climateinitiativesplatform.org/index.php/European_Initiative_for_Sustainable_Development_in_Agriculture_(EISA)",
  "https://climateinitiativesplatform.org/index.php/European_Technology_and_Innovation_Platform_for_Wind_(ETIPwind)",
  "https://climateinitiativesplatform.org/index.php/EV100",
  "https://climateinitiativesplatform.org/index.php/EverGreen_Agriculture_Partnership",
  "https://climateinitiativesplatform.org/index.php/Exponential_Roadmap_Initiative",
  "https://climateinitiativesplatform.org/index.php/Faith_for_Earth",
  "https://climateinitiativesplatform.org/index.php/Fashion_Industry_Charter_for_Climate_Action",
  "https://climateinitiativesplatform.org/index.php/Food_Security_Climate_Resilience_Facility",
  "https://climateinitiativesplatform.org/index.php/Forest_Carbon_Partnership_Facility_(FCPF)",
  "https://climateinitiativesplatform.org/index.php/Forest_Stewardship_Council",
  "https://climateinitiativesplatform.org/index.php/Forest_Trends",
  "https://climateinitiativesplatform.org/index.php/Fossil_Free_-_Divest_from_Fossil_Fuels",
  "https://climateinitiativesplatform.org/index.php/Getting_to_Zero_Coalition",
  "https://climateinitiativesplatform.org/index.php/Global_100%25_RE",
  "https://climateinitiativesplatform.org/index.php/Global_Alliance_for_Buildings_and_Construction",
  "https://climateinitiativesplatform.org/index.php/Global_Alliance_for_Clean_Cookstoves",
  "https://climateinitiativesplatform.org/index.php/Global_Alliance_for_Climate-Smart_Agriculture",
  "https://climateinitiativesplatform.org/index.php/Global_Alliance_for_Energy_Productivity",
  "https://climateinitiativesplatform.org/index.php/Global_Bioenergy_Partnership",
  "https://climateinitiativesplatform.org/index.php/Global_Buildings_Performance_Network_(GBPN)",
  "https://climateinitiativesplatform.org/index.php/Global_CCS_Institute",
  "https://climateinitiativesplatform.org/index.php/Global_Clean_Water_Desalination_Alliance_(GCWDA)",
  "https://climateinitiativesplatform.org/index.php/Global_Commons_Alliance",
  "https://climateinitiativesplatform.org/index.php/Global_Cool_Cities_Alliance_(GCCA)",
  "https://climateinitiativesplatform.org/index.php/Global_Covenant_of_Mayors_for_Climate_%26_Energy",
  "https://climateinitiativesplatform.org/index.php/Global_e-Sustainability_Initiative_(GeSI)",
  "https://climateinitiativesplatform.org/index.php/Global_Facility_for_Disaster_Reduction_and_Recovery",
  "https://climateinitiativesplatform.org/index.php/Global_Food_Cold_Chain_Council_(GFCCC)",
  "https://climateinitiativesplatform.org/index.php/Global_Fuel_Economy_Initiative_(GFEI)",
  "https://climateinitiativesplatform.org/index.php/Global_Gas_Flaring_Reduction_Partnership",
  "https://climateinitiativesplatform.org/index.php/Global_Geothermal_Alliance",
  "https://climateinitiativesplatform.org/index.php/Global_Investor_Coalition_on_Climate_Change_(GIC)",
  "https://climateinitiativesplatform.org/index.php/Global_Lead_City_Network_on_Sustainable_Procurement_(GLCN)",
  "https://climateinitiativesplatform.org/index.php/Global_Methane_Initiative",
  "https://climateinitiativesplatform.org/index.php/Global_Partnership_on_Forest_and_Landscape_Restoration_(GPFLR)",
  "https://climateinitiativesplatform.org/index.php/Global_Reporting_Initiative",
  "https://climateinitiativesplatform.org/index.php/Global_Research_Alliance_on_Agricultural_Greenhouse_Gases",
  "https://climateinitiativesplatform.org/index.php/Global_Resilience_Partnership",
  "https://climateinitiativesplatform.org/index.php/Global_Solar_Council_(GSC)",
  "https://climateinitiativesplatform.org/index.php/Global_Subsidies_Initiative_(GSI)",
  "https://climateinitiativesplatform.org/index.php/Global_Wind_Energy_Council_(GWEC)",
  "https://climateinitiativesplatform.org/index.php/Go_100%25",
  "https://climateinitiativesplatform.org/index.php/Gold_Standard",
  "https://climateinitiativesplatform.org/index.php/Governors%27_Climate_and_Forests_Task_Force_(GCF)",
  "https://climateinitiativesplatform.org/index.php/Great_Green_Wall_for_Sahara_and_the_Sahel_Initiative_(GGWSSI)",
  "https://climateinitiativesplatform.org/index.php/Green_Freight_Asia_Network_(GFAN)",
  "https://climateinitiativesplatform.org/index.php/Green_Growth_Partnership",
  "https://climateinitiativesplatform.org/index.php/Haga_Initiative",
  "https://climateinitiativesplatform.org/index.php/ICLEI_-_Local_Governments_for_Sustainability",
  "https://climateinitiativesplatform.org/index.php/IEA_Technology_Collaboration_Programme_on_Energy_Efficient_End-Use_Equipment_(4E)",
  "https://climateinitiativesplatform.org/index.php/Implement_the_Recommendations_of_the_Task_Force_on_Climate_Related_Disclosures",
  "https://climateinitiativesplatform.org/index.php/Initiative_20x20",
  "https://climateinitiativesplatform.org/index.php/Initiative_for_Coal_Regions_in_Transition",
  "https://climateinitiativesplatform.org/index.php/Institutional_Investors_Group_for_Climate_Change_(IIGCC)",
  "https://climateinitiativesplatform.org/index.php/InsuResilience_Global_Partnership",
  "https://climateinitiativesplatform.org/index.php/Interfaith_Rainforest_Initiative",
  "https://climateinitiativesplatform.org/index.php/International_Alliance_to_Combat_Ocean_Acidification",
  "https://climateinitiativesplatform.org/index.php/International_Carbon_Action_Partnership",
  "https://climateinitiativesplatform.org/index.php/International_Coalition_for_Sustainable_Aviation_(ICSA)",
  "https://climateinitiativesplatform.org/index.php/International_Corel_Reef_Initiative_(ICRI)",
  "https://climateinitiativesplatform.org/index.php/International_Council_on_Clean_Transportation_(ICCT)",
  "https://climateinitiativesplatform.org/index.php/International_Development_Finance_Club_(IDFC)",
  "https://climateinitiativesplatform.org/index.php/International_Partnership_for_Energy_Efficiency_Cooperation_(IPEEC)",
  "https://climateinitiativesplatform.org/index.php/International_Petroleum_Industry_Environmental_Conservation_Association_(IPIECA)",
  "https://climateinitiativesplatform.org/index.php/International_Solar_Alliance",
  "https://climateinitiativesplatform.org/index.php/International_Zero-Emission_Vehicle_Alliance_(ZEV_Alliance)",
  "https://climateinitiativesplatform.org/index.php/Investor_Network_on_Climate_Risk_(INCR)",
  "https://climateinitiativesplatform.org/index.php/Joint_Work_Programme_on_Resilient_Cities_(JWP)",
  "https://climateinitiativesplatform.org/index.php/LCTPi_Cement_Sustainability_Initiative",
  "https://climateinitiativesplatform.org/index.php/LCTPi_Climate_Smart_Agriculture",
  "https://climateinitiativesplatform.org/index.php/LCTPI_Low_Carbon_Technology_Partnership_initiative_(Main)",
  "https://climateinitiativesplatform.org/index.php/LCTPi_Renewables",
  "https://climateinitiativesplatform.org/index.php/Leadership_for_Urban_Climate_Investment_(LUCI)",
  "https://climateinitiativesplatform.org/index.php/Leadership_Group_for_Industry_Transition_(LeadIT)",
  "https://climateinitiativesplatform.org/index.php/Lean_and_Green",
  "https://climateinitiativesplatform.org/index.php/Life_Beef_Carbon_Initiative",
  "https://climateinitiativesplatform.org/index.php/Logistics_Emission_Reduction_Scheme_(LERS)",
  "https://climateinitiativesplatform.org/index.php/Low_Carbon_Road_and_Road_Transport_Initiative",
  "https://climateinitiativesplatform.org/index.php/Low_Carbon_Vehicle_Partnership_(LowCVP)",
  "https://climateinitiativesplatform.org/index.php/Low_Emissions_Development_Strategies_(LEDS)_Global_Partnership",
  "https://climateinitiativesplatform.org/index.php/Low-Carbon_Sustainable_Rail_Transport_Challenge",
  "https://climateinitiativesplatform.org/index.php/Megacities_Alliance_for_Water_and_Climate",
  "https://climateinitiativesplatform.org/index.php/Mexico_City_Pact",
  "https://climateinitiativesplatform.org/index.php/Milan_Urban_Food_Policy_Pact",
  "https://climateinitiativesplatform.org/index.php/Mission_Innovation",
  "https://climateinitiativesplatform.org/index.php/MobiliseYourCity_Partnership",
  "https://climateinitiativesplatform.org/index.php/Montreal_Carbon_Pledge",
  "https://climateinitiativesplatform.org/index.php/Nature4Climate",
  "https://climateinitiativesplatform.org/index.php/Navigating_a_Changing_Climate",
  "https://climateinitiativesplatform.org/index.php/Net_Zero_Carbon_Buildings_Commitment",
  "https://climateinitiativesplatform.org/index.php/Net-Zero_2050",
  "https://climateinitiativesplatform.org/index.php/Net-Zero_Asset_Owner_Alliance",
  "https://climateinitiativesplatform.org/index.php/New_Vision_for_Agriculture",
  "https://climateinitiativesplatform.org/index.php/North_American_Climate_Smart_Agriculture_Alliance_(NACSAA)",
  "https://climateinitiativesplatform.org/index.php/Ocean_Renewable_Energy_Action_Coalition",
  "https://climateinitiativesplatform.org/index.php/Ocean_Risk_and_Resilience_Action_Alliance_(ORRAA)",
  "https://climateinitiativesplatform.org/index.php/Oil_and_Gas_Climate_Initiative",
  "https://climateinitiativesplatform.org/index.php/One_Planet_Business_for_Biodiversity_(OP2B)",
  "https://climateinitiativesplatform.org/index.php/PACMUN_project",
  "https://climateinitiativesplatform.org/index.php/Palm_Oil_Innovation_Group_(POIG)",
  "https://climateinitiativesplatform.org/index.php/Paris_Declaration_on_Electromobility_on_Climate_Change",
  "https://climateinitiativesplatform.org/index.php/Paris_Pact_on_Water_and_Adaptation",
  "https://climateinitiativesplatform.org/index.php/Partnership_on_Transparency_in_the_Paris_Agreement",
  "https://climateinitiativesplatform.org/index.php/Planners_for_Climate_Action_(P4CA)",
  "https://climateinitiativesplatform.org/index.php/Portfolio_Decarbonization_Coalition",
  "https://climateinitiativesplatform.org/index.php/Powering_Past_Coal_Alliance",
  "https://climateinitiativesplatform.org/index.php/Prince_of_Wales%27s_Corporate_Leaders_Group",
  "https://climateinitiativesplatform.org/index.php/Private_Financing_Advisory_Network_(PFAN)",
  "https://climateinitiativesplatform.org/index.php/Promotion_of_Smart_Agriculture_Towards_Climate_Change",
  "https://climateinitiativesplatform.org/index.php/Protection_of_400_million_Hectares_of_Forests",
  "https://climateinitiativesplatform.org/index.php/Public_Transport_Declaration_on_Climate_Leadership_(UITP)",
  "https://climateinitiativesplatform.org/index.php/R20",
  "https://climateinitiativesplatform.org/index.php/R4_Rural_Resilience_Initiative",
  "https://climateinitiativesplatform.org/index.php/Rainforest_Alliance",
  "https://climateinitiativesplatform.org/index.php/RE100",
  "https://climateinitiativesplatform.org/index.php/REDD%2B_Partnership",
  "https://climateinitiativesplatform.org/index.php/Reduce_Short-Lived_Climate_Pollutant_Emissions",
  "https://climateinitiativesplatform.org/index.php/Refrigerants,_Naturally!",
  "https://climateinitiativesplatform.org/index.php/RegionsAdapt",
  "https://climateinitiativesplatform.org/index.php/Remove_commodity-driven_deforestation",
  "https://climateinitiativesplatform.org/index.php/REN_Alliance",
  "https://climateinitiativesplatform.org/index.php/REN21_(Renewable_Energy_Policy_Network_for_the_21st_Century)",
  "https://climateinitiativesplatform.org/index.php/Renewable_Energy_and_Energy_Efficiency_Partnership_(REEEP)",
  "https://climateinitiativesplatform.org/index.php/Renovate_Europe",
  "https://climateinitiativesplatform.org/index.php/Responsible_Corporate_Engagement_in_Climate_Policy",
  "https://climateinitiativesplatform.org/index.php/Risk-informed_Early_Action_Partnership_(REAP)",
  "https://climateinitiativesplatform.org/index.php/Roundtable_on_Sustainable_Biomaterials_(RSB_Standard)",
  "https://climateinitiativesplatform.org/index.php/Roundtable_on_Sustainable_Palm_Oil_(RSPO)",
  "https://climateinitiativesplatform.org/index.php/Save_Food_initiative",
  "https://climateinitiativesplatform.org/index.php/Science_Based_Targets_initiative",
  "https://climateinitiativesplatform.org/index.php/SeaCargo_Charter",
  "https://climateinitiativesplatform.org/index.php/SEforAll:_Building_Efficiency_Accelerator",
  "https://climateinitiativesplatform.org/index.php/SEforAll:_District_Energy_Initiative",
  "https://climateinitiativesplatform.org/index.php/SEforAll:_Global_Energy_Efficiency_Accelerator_Platform_(Main)",
  "https://climateinitiativesplatform.org/index.php/SEforAll:_Industrial_Energy_Efficiency_Accelerator",
  "https://climateinitiativesplatform.org/index.php/SIDS_Lighthouses_Initiative",
  "https://climateinitiativesplatform.org/index.php/SLoCat_Partnership_on_Sustainable,_Low_Carbon_Transport",
  "https://climateinitiativesplatform.org/index.php/Smart_Risk_Investing_(SRI)",
  "https://climateinitiativesplatform.org/index.php/SME_Climate_Hub",
  "https://climateinitiativesplatform.org/index.php/Sports_for_Climate_Action",
  "https://climateinitiativesplatform.org/index.php/Statement_by_Financial_Institutions_on_Energy_Efficiency_Finance",
  "https://climateinitiativesplatform.org/index.php/States_and_Regions_Annual_Disclosure",
  "https://climateinitiativesplatform.org/index.php/Step_Up_Declaration:_Powering_Mission_2020",
  "https://climateinitiativesplatform.org/index.php/SUNx",
  "https://climateinitiativesplatform.org/index.php/Super-efficient_Equipment_and_Appliance_Deployment_(SEAD)_Initiative",
  "https://climateinitiativesplatform.org/index.php/Sustainable_Agriculture_Initiative_(SAI)_Platform",
  "https://climateinitiativesplatform.org/index.php/Sustainable_Agriculture_Network_(SAN)",
  "https://climateinitiativesplatform.org/index.php/Sustainable_Mobility_for_All_(SUM4ALL)",
  "https://climateinitiativesplatform.org/index.php/Sustainable_Procurement",
  "https://climateinitiativesplatform.org/index.php/Sustainable_Shipping_Initiative",
  "https://climateinitiativesplatform.org/index.php/Taxi4SmartCities",
  "https://climateinitiativesplatform.org/index.php/The_1-in-100_Initiative",
  "https://climateinitiativesplatform.org/index.php/The_30X30_Forests,_Food_and_Land_Challenge",
  "https://climateinitiativesplatform.org/index.php/The_Blue_Carbon_Initiative",
  "https://climateinitiativesplatform.org/index.php/The_Climate_Group",
  "https://climateinitiativesplatform.org/index.php/The_Climate_Pledge",
  "https://climateinitiativesplatform.org/index.php/The_Climate_Registry",
  "https://climateinitiativesplatform.org/index.php/The_Global_Forum_on_Agriculture_Research_(GFAR)",
  "https://climateinitiativesplatform.org/index.php/The_New_York_Declaration_on_Forests",
  "https://climateinitiativesplatform.org/index.php/Three_Percent_Club_for_Energy_Efficiency",
  "https://climateinitiativesplatform.org/index.php/Transformative_Actions_Program_(TAP)",
  "https://climateinitiativesplatform.org/index.php/Transformative_Urban_Mobility_Initiative_(TUMI)",
  "https://climateinitiativesplatform.org/index.php/Transition_Network",
  "https://climateinitiativesplatform.org/index.php/Transition_Pathway_Initiative_(TPI)",
  "https://climateinitiativesplatform.org/index.php/Transport_Decarbonisation_Alliance_(TDA)",
  "https://climateinitiativesplatform.org/index.php/Tropical_Forest_Alliance_(TFA)",
  "https://climateinitiativesplatform.org/index.php/UN-REDD_Programme",
  "https://climateinitiativesplatform.org/index.php/Under_2_Coalition",
  "https://climateinitiativesplatform.org/index.php/UNEP_Finance_Initiative_(UNEP-FI)",
  "https://climateinitiativesplatform.org/index.php/UNEP_Partnership_for_Clean_Fuels_and_Vehicles_(PCFV)",
  "https://climateinitiativesplatform.org/index.php/United_for_Efficiency",
  "https://climateinitiativesplatform.org/index.php/United_Nations-Convened_Net_Zero_Asset_Owner_Alliance",
  "https://climateinitiativesplatform.org/index.php/United_Smart_Cities",
  "https://climateinitiativesplatform.org/index.php/United_States_Climate_Alliance",
  "https://climateinitiativesplatform.org/index.php/Urban_Electric_Mobility_Initiative",
  "https://climateinitiativesplatform.org/index.php/Urban_Transitions_Alliance",
  "https://climateinitiativesplatform.org/index.php/Urban-LEDS_project",
  "https://climateinitiativesplatform.org/index.php/Value_Chain_Risk_to_Resilience",
  "https://climateinitiativesplatform.org/index.php/Vote_Solar_Initiative",
  "https://climateinitiativesplatform.org/index.php/Walk_21",
  "https://climateinitiativesplatform.org/index.php/WBCSD_Urban_Infrastructure_Initiative",
  "https://climateinitiativesplatform.org/index.php/We_are_still_in",
  "https://climateinitiativesplatform.org/index.php/We_Mean_Business",
  "https://climateinitiativesplatform.org/index.php/World_Green_Building_Council",
  "https://climateinitiativesplatform.org/index.php/World_Mayors_Council_on_Climate_Change_(WMCCC)",
  "https://climateinitiativesplatform.org/index.php/WWF_Climate_Business_Network",
  "https://climateinitiativesplatform.org/index.php/Zero_Carbon_Buildings_for_All",
  "https://climateinitiativesplatform.org/index.php/Zero_Deforestation_Commitments_from_Commodity_Producers_and_Traders",
  "https://climateinitiativesplatform.org/index.php/Zero_Routine_Flaring_by_2030"
]

# Function to crawl a single page and extract data
def crawl_page(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    rows = soup.find_all('tr')

    d = {}
    for row in rows:
      row = list(filter(lambda x: x != "\n", row.contents))
      if len(row) == 2:
        label = row[0].text.strip()#.replace(" ", "_")
        d[label] = row[1].text.strip()

    themes = soup.find("table", {"class": "narrow-th-table"})
    
    themeLabels = list( filter( lambda x: x!="", themes.contents[1].text.strip().split('\n') ) ) 
    themeValues = list( filter( lambda x: x!="", themes.contents[3].text.strip().split('\n') ) ) 
        
    for i in range( len(themeValues) ) :
      d[themeLabels[i]] = themeValues[i]
     
    # Return the extracted data as a dictionary
    return d

# Main function to crawl the main page and linked pages
def crawl_website():
    data = []  # To store the extracted data

    # Crawl each linked page and extract data
    for link in links:
        page_data = crawl_page(link)
        data.append(page_data)

    # Save the data to a CSV file
    keys = data[0].keys()
    print(data)
    filename = 'climate_data.csv'

    with open(filename, 'w', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, extrasaction='ignore', fieldnames=keys)
        writer.writeheader()
        writer.writerows(data)

    print(f'Data saved to {filename}')

# Call the main function to start crawling
crawl_website()
